### ISSUE TITLE
Could not find a type definition associated with type [xlrelease.Tile] with XLR 4.8.1

### ISSUE THREAD

**Issue by steve4px** [xebialabs-community/xlr-xldeploy-plugin#35]
Is this version 2.7.0 of this plugin compatible with XLR version 4.8.1? The Readme states 4.8+  this error  prevents XLR from starting up.

**Comment by jdewinne** [comment]
Oh, correct. I'll update the readme, as tiles are only supported since 5.x.
What you can do is, open up the jar file, and edit the `synthetic.xml`. I think if you remove this type: [xldeploy.XLDVersionsTile](https://github.com/xebialabs-community/xlr-xldeploy-plugin/blob/master/src/main/resources/synthetic.xml#L177) it should work also in 4.8.x.

**Comment by steve4px** [comment]
I figured that. Modifying the synth allows it to start up.
