### ISSUE TITLE
Migrate Task should not fail if package exists

### ISSUE THREAD

**Issue by bbonn** [xebialabs-community/xlr-xldeploy-plugin#48]
Hi There,

This is more of a feature than an issue I suppose.   We have a user with a migrate task in there template which they use through numerous environments.   So generally the package is migrated during the release to the early environment.   Then the next time the release runs the migrate task fails because the package exists.  I was thinking it would be better to just give a message and move on if it already exists since no harm is done.   For now I have them using "does ci exist" then using the boolean to decide whether or not to skip the migrate task.   

I believe it is the fetch2 function that errors out if the package exists.   Again we have a workaround, consider it a feature request :)

Thanks,
Bernie

**Comment by bbonn** [comment]
Here is the error:

Failed to import package. Server return [400], with content [Already imported version ens_Official_360 of application ensdda]

**Comment by istairbn** [comment]
There are three possible answers to a migrate 400 response:

1. Assume the existing package is correct (catch the 400, complete the task)
2. Force the current package up (catch the 400, remove the current application, redo the migrate)
3. Require user to confirm (current implementation, fail task)

1 is the equivalent of an existence check. The task completes but we don't know for sure that the correct package is in place. All we know is that a package exists with the same name. Is that robust enough? Maybe checking the checksum at least to confirm that they match? 

2 is the equivalent of an overwrite. Would we not be better offering an "overwrite" as an option? Since the user has specifically asked for Package X to be migrated, that would assure the package is correct. That way we don't care what was there before. This makes it idempotent (it'll run every time without failing) whilst assuring that the users request is respected. It would still be an option - because users would have to select it - meaning that users preferring to leave it alone could do the existence check.

**Comment by bbonn** [comment]
Hey Ben, 

Thanks for this great write-up.   I am with you option 2 seems to make a lot of sense.   And it includes the word idempotent, which makes the bosses here very happy. :)

**Comment by jdewinne** [comment]
Merged onto master branch, not released yet.

**Comment by jdewinne** [comment]
Available in v2.9.0
